In [1]:
import numpy as np

In [4]:
myList = [1,2,3,4,5]
myArr = np.array(myList)
print(myArr)
type(myArr)

[1 2 3 4 5]


numpy.ndarray

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [13]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.random.rand(5, 2)

array([[0.20840236, 0.07837715],
       [0.95896304, 0.27227279],
       [0.50810042, 0.54038012],
       [0.88876522, 0.33544685],
       [0.09463917, 0.37837044]])

In [15]:
np.random.randint(0, 100, (5, 2))

array([[84, 56],
       [ 5, 73],
       [51, 12],
       [87, 88],
       [97,  0]])

## Numpy Indexing and Selection

In [4]:
arr1 = np.arange(1, 10)
print(arr1[5:])
print(arr1[:10])
print(arr1[0:10])

[6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [5]:
arr1[:5] = 100
arr1

array([100, 100, 100, 100, 100,   6,   7,   8,   9])

In [8]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])
res = dice_rolls[dice_rolls > 2]
len(res)

19

## NumPy Operations

In [10]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.

import numpy as np
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

account_total =  account_transactions.sum()
account_total

2720